import NextHead from "next/head";

export const Head = ({ pageName }: { pageName: string }) => (
  <NextHead>
    <title>{pageName}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </NextHead>
);
